export const mockUsers = [
  {
    id: "user-1",
    name: "Atty. Jane Doe",
    email: "jane.doe@legalmind.com",
    password: "password123",
    role: "lawyer",
    phone: "+1-555-0101",
    specialization: "Corporate Law",
    caseCount: 8,
    avatar: "👩‍⚖️",
  },
  {
    id: "user-2",
    name: "John Smith",
    email: "john.smith@acmecorp.com",
    password: "password123",
    role: "client",
    phone: "+1-555-0102",
    company: "ACME Corp",
    avatar: "👨‍💼",
  },
  {
    id: "user-3",
    name: "Atty. John Smith",
    email: "john.smith@legalmind.com",
    password: "password123",
    role: "lawyer",
    phone: "+1-555-0103",
    specialization: "Intellectual Property",
    caseCount: 6,
    avatar: "👨‍⚖️",
  },
  {
    id: "user-4",
    name: "Alice Johnson",
    email: "alice.johnson@alphalabs.com",
    password: "password123",
    role: "client",
    phone: "+1-555-0104",
    company: "Alpha Labs",
    avatar: "👩‍💻",
  },
  {
    id: "user-5",
    name: "Admin User",
    email: "admin@legalmind.com",
    password: "admin123",
    role: "admin",
    phone: "+1-555-0105",
    avatar: "👤",
  },
];

// Mock Cases
export const mockCases = [
  {
    id: "case-1",
    title: "Contract Dispute - ACME vs. Smith",
    client: "ACME Corp",
    clientId: "user-2",
    lawyerId: "user-1",
    lawyer: "Atty. Jane Doe",
    status: "In Progress",
    priority: "High",
    nextHearing: "2025-01-15",
    tags: ["contract", "civil"],
    summary: "Breach of contract regarding delivery timelines.",
    description:
      "Dispute over delivery obligations in the Master Service Agreement. Client claims vendor failed to meet agreed-upon delivery dates, resulting in operational delays.",
    caseType: "Civil Litigation",
    filingDate: "2024-11-20",
    amount: "$150,000",
    progress: 65,
  },
  {
    id: "case-2",
    title: "IP Infringement - Alpha Labs",
    client: "Alpha Labs",
    clientId: "user-4",
    lawyerId: "user-3",
    lawyer: "Atty. John Smith",
    status: "Discovery",
    priority: "High",
    nextHearing: "2025-02-02",
    tags: ["ip", "patent"],
    summary: "Alleged patent infringement on biotech process.",
    description:
      "Defendant accused of utilizing our patented process without authorization. We are in the discovery phase gathering evidence.",
    caseType: "Intellectual Property",
    filingDate: "2024-10-05",
    amount: "$500,000",
    progress: 40,
  },
  {
    id: "case-3",
    title: "Employment Dispute - HR Matter",
    client: "ACME Corp",
    clientId: "user-2",
    lawyerId: "user-1",
    lawyer: "Atty. Jane Doe",
    status: "On Hold",
    priority: "Medium",
    nextHearing: "2025-03-10",
    tags: ["employment", "hr"],
    summary: "Employment termination dispute.",
    description:
      "Wrongful termination claim filed by former employee. Currently awaiting mediation.",
    caseType: "Employment Law",
    filingDate: "2024-12-01",
    amount: "$75,000",
    progress: 25,
  },
  {
    id: "case-4",
    title: "Real Estate Acquisition",
    client: "Tech Ventures LLC",
    clientId: "user-2",
    lawyerId: "user-1",
    lawyer: "Atty. Jane Doe",
    status: "Closed",
    priority: "Low",
    nextHearing: null,
    tags: ["real-estate", "commercial"],
    summary: "Commercial property acquisition completed.",
    description:
      "Successfully closed acquisition of commercial property in downtown district.",
    caseType: "Real Estate",
    filingDate: "2024-08-15",
    closedDate: "2024-11-30",
    amount: "$2,500,000",
    progress: 100,
  },
];

// Mock Documents
export const mockDocuments = [
  {
    id: "doc-1",
    caseId: "case-1",
    title: "Master Service Agreement.pdf",
    type: "pdf",
    uploadedBy: "John Smith",
    uploadedAt: "2024-12-20",
    notes: "Key clauses on delivery timelines and penalties.",
    size: "2.4 MB",
    url: "#",
  },
  {
    id: "doc-2",
    caseId: "case-2",
    title: "Prior Art Summary.docx",
    type: "docx",
    uploadedBy: "Atty. John Smith",
    uploadedAt: "2024-12-22",
    notes: "Summaries of related patents for defense.",
    size: "1.8 MB",
    url: "#",
  },
  {
    id: "doc-3",
    caseId: "case-1",
    title: "Contract Amendment #2.pdf",
    type: "pdf",
    uploadedBy: "Atty. Jane Doe",
    uploadedAt: "2024-12-15",
    notes: "Amendments to original contract.",
    size: "0.9 MB",
    url: "#",
  },
  {
    id: "doc-4",
    caseId: "case-2",
    title: "Patent Infringement Evidence.pdf",
    type: "pdf",
    uploadedBy: "Atty. John Smith",
    uploadedAt: "2024-12-18",
    notes: "Technical analysis showing similarity to patented process.",
    size: "3.2 MB",
    url: "#",
  },
  {
    id: "doc-5",
    caseId: "case-3",
    title: "Employee Contract.pdf",
    type: "pdf",
    uploadedBy: "HR Department",
    uploadedAt: "2024-12-01",
    notes: "Original employment contract.",
    size: "0.7 MB",
    url: "#",
  },
];

// Mock Chat Messages
export const mockMessages = [
  {
    id: "msg-1",
    caseId: "case-1",
    from: "Client",
    fromId: "user-2",
    to: "Lawyer",
    toId: "user-1",
    text: "Can we finalize the clause on delivery by next week?",
    timestamp: "2024-12-28T09:30:00Z",
  },
  {
    id: "msg-2",
    caseId: "case-1",
    from: "Lawyer",
    fromId: "user-1",
    to: "Client",
    toId: "user-2",
    text: "Yes, I will share a revised draft tomorrow.",
    timestamp: "2024-12-28T10:00:00Z",
  },
  {
    id: "msg-3",
    caseId: "case-1",
    from: "Client",
    fromId: "user-2",
    to: "Lawyer",
    toId: "user-1",
    text: "Perfect. What about the penalty clause?",
    timestamp: "2024-12-28T10:45:00Z",
  },
  {
    id: "msg-4",
    caseId: "case-2",
    from: "Lawyer",
    fromId: "user-3",
    to: "Client",
    toId: "user-4",
    text: "Discovery phase is progressing well. We have identified 5 key witnesses.",
    timestamp: "2024-12-27T14:20:00Z",
  },
  {
    id: "msg-5",
    caseId: "case-2",
    from: "Client",
    fromId: "user-4",
    to: "Lawyer",
    toId: "user-3",
    text: "Excellent. When can we expect depositions?",
    timestamp: "2024-12-27T15:00:00Z",
  },
];

// Mock Events/Reminders
export const mockReminders = [
  {
    id: "reminder-1",
    caseId: "case-1",
    title: "Next Hearing",
    date: "2025-01-15",
    type: "hearing",
    priority: "high",
    completed: false,
  },
  {
    id: "reminder-2",
    caseId: "case-2",
    title: "Submit Discovery Documents",
    date: "2025-01-08",
    type: "deadline",
    priority: "high",
    completed: false,
  },
  {
    id: "reminder-3",
    caseId: "case-1",
    title: "Client Meeting",
    date: "2025-01-12",
    type: "meeting",
    priority: "medium",
    completed: false,
  },
  {
    id: "reminder-4",
    caseId: "case-3",
    title: "Mediation Session",
    date: "2025-01-20",
    type: "mediation",
    priority: "high",
    completed: false,
  },
];

// Mock RAG Search Results
export const mockRAGResults = [
  {
    id: "rag-1",
    query: "What are the delivery penalties?",
    answer:
      "According to Section 3.2 of the Master Service Agreement, delivery penalties are calculated as 5% of the monthly service fee for each day the delivery is delayed beyond the agreed date. Maximum penalty is capped at 20% of the monthly service fee.",
    source: "Master Service Agreement.pdf",
    relevance: 0.95,
    snippet:
      "The Vendor shall deliver services by the agreed date. Failure to do so results in penalties as follows: 5% per day, capped at 20%.",
  },
  {
    id: "rag-2",
    query: "Contract termination clauses",
    answer:
      "Either party may terminate this agreement with 30 days written notice if the other party materially breaches and fails to remedy within 15 days of notification.",
    source: "Master Service Agreement.pdf",
    relevance: 0.88,
    snippet:
      "Termination: Either party may terminate upon material breach and 15-day cure period.",
  },
];

// Mock Case Outcome Predictions
export const mockPredictions = [
  {
    id: "pred-1",
    caseId: "case-1",
    predictedOutcome: "Favorable Settlement",
    probability: 0.78,
    confidence: 0.85,
    factors: [
      "Strong contractual language in favor of client",
      "Clear breach by defendant",
      "Similar cases favor our position",
    ],
  },
  {
    id: "pred-2",
    caseId: "case-2",
    predictedOutcome: "Court Victory",
    probability: 0.72,
    confidence: 0.82,
    factors: [
      "Patent was filed before defendant's work",
      "Technical evidence strongly supports infringement",
      "Defendant has limited prior art defense",
    ],
  },
];

// Mock Summaries
export const mockSummaries = [
  {
    id: "summary-1",
    documentId: "doc-1",
    title: "Master Service Agreement Summary",
    summary:
      "This is a comprehensive service agreement between ACME Corp and the service provider. Key terms include: (1) Service delivery within 30 days, (2) Monthly fees of $50,000, (3) Penalties for late delivery at 5% per day, (4) 12-month term with auto-renewal, (5) Either party can terminate with 30 days notice after material breach and 15-day cure period.",
  },
];

// Mock Activity Log
export const mockActivityLog = [
  {
    id: "activity-1",
    caseId: "case-1",
    action: "Document uploaded",
    detail: "Contract Amendment #2.pdf",
    timestamp: "2024-12-28T14:30:00Z",
    user: "Atty. Jane Doe",
  },
  {
    id: "activity-2",
    caseId: "case-1",
    action: "Status updated",
    detail: "Changed from Discovery to In Progress",
    timestamp: "2024-12-28T10:15:00Z",
    user: "Atty. Jane Doe",
  },
  {
    id: "activity-3",
    caseId: "case-2",
    action: "Message sent",
    detail: "Lawyer sent update to client",
    timestamp: "2024-12-27T14:20:00Z",
    user: "Atty. John Smith",
  },
];

// Notifications for different user roles
export const mockNotifications = {
  admin: [
    {
      id: "notif-admin-1",
      type: "alert",
      title: "System Update Required",
      message:
        "New security patches available. Please schedule maintenance window.",
      timestamp: "2024-12-09T09:00:00Z",
      read: false,
      priority: "high",
      icon: "🔔",
    },
    {
      id: "notif-admin-2",
      type: "info",
      title: "New User Registration",
      message: "5 new users registered today. Pending account verification.",
      timestamp: "2024-12-09T07:30:00Z",
      read: false,
      priority: "medium",
      icon: "👥",
    },
    {
      id: "notif-admin-3",
      type: "warning",
      title: "Storage Capacity Alert",
      message: "Document storage is at 85% capacity. Consider upgrading plan.",
      timestamp: "2024-12-08T16:45:00Z",
      read: true,
      priority: "high",
      icon: "⚠️",
    },
  ],
  lawyer: [
    {
      id: "notif-lawyer-1",
      type: "reminder",
      title: "Upcoming Hearing Tomorrow",
      message: "Case: Contract Dispute - ACME vs. Smith at 10:00 AM",
      timestamp: "2024-12-09T08:00:00Z",
      read: false,
      priority: "high",
      icon: "⚖️",
    },
    {
      id: "notif-lawyer-2",
      type: "document",
      title: "New Document Uploaded",
      message: "Client uploaded 'Evidence_Photos.pdf' to Case #IP-2024-102",
      timestamp: "2024-12-09T06:15:00Z",
      read: false,
      priority: "medium",
      icon: "📄",
    },
    {
      id: "notif-lawyer-3",
      type: "message",
      title: "Client Message",
      message: "John Smith sent you a message regarding case timeline.",
      timestamp: "2024-12-08T14:20:00Z",
      read: true,
      priority: "medium",
      icon: "💬",
    },
  ],
  client: [
    {
      id: "notif-client-1",
      type: "update",
      title: "Case Status Updated",
      message: "Your case 'Contract Dispute' has moved to Discovery phase.",
      timestamp: "2024-12-09T10:30:00Z",
      read: false,
      priority: "high",
      icon: "📋",
    },
    {
      id: "notif-client-2",
      type: "message",
      title: "Message from Lawyer",
      message: "Atty. Jane Doe sent you an update about your case.",
      timestamp: "2024-12-09T05:45:00Z",
      read: false,
      priority: "medium",
      icon: "💬",
    },
    {
      id: "notif-client-3",
      type: "reminder",
      title: "Document Request",
      message: "Please upload the signed contract by Dec 15, 2024.",
      timestamp: "2024-12-08T11:00:00Z",
      read: true,
      priority: "high",
      icon: "📎",
    },
  ],
};
